# Generated by Django 5.2.4 on 2025-07-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirIndiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('depart_from', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=20)),
                ('arrival_time', models.DateTimeField()),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='GoFirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('depart_from', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=20)),
                ('arrival_time', models.DateTimeField()),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='IndigoModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('depart_from', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=20)),
                ('arrival_time', models.DateTimeField()),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SpiceJetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('depart_from', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=20)),
                ('arrival_time', models.DateTimeField()),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='VistaraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('depart_from', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('destination', models.CharField(max_length=20)),
                ('arrival_time', models.DateTimeField()),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
