# Generated by Django 5.2.4 on 2025-07-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='flight_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
